FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY ./target/orderlakehouse-kafka-producer-generic-svc-1.0-SNAPSHOT.jar .
ENTRYPOINT [ "java", "-jar", "orderlakehouse-kafka-producer-generic-svc-1.0-SNAPSHOT.jar" ]