spring:
  application:
    name: orderlakehouse-producer-svc
  kafka:
    bootstrap-servers:
      - orderLakeHouseKafka091Node1:9092
      - orderLakeHouseKafka091Node2:9092
      - orderLakeHouseKafka091Node3:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false 

server:
  port: 8081